create DATABASE QL_KS2

use QL_KS2

drop table NHANVIEN
drop table HOADON
drop table KHACHHANG
drop table PHONG
drop table TAIKHOAN

create table TAIKHOAN(
TENTK VARCHAR(150) NOT NULL,
MATKHAU VARCHAR(150) NOT NULL,

MANV INT NOT NULL,
CONSTRAINT PK_TAIKHOAN PRIMARY KEY (MANV),
CONSTRAINT FK_TAIKHOAN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)
CREATE TABLE PHONG(
MAPHONG INT IDENTITY(1,1) PRIMARY KEY,
SOPHONG VARCHAR(255) NOT NULL,
LOAIPHONG NVARCHAR(250) NOT NULL,

GIUONG NVARCHAR(250) NOT NULL,
GIA BIGINT NOT NULL,
DATPHONG VARCHAR (50) DEFAULT('NO') NULL
);

CREATE TABLE KHACHHANG(
    MAKH INT IDENTITY(1,1) PRIMARY KEY,
    TENKH NVARCHAR(250) NOT NULL,
    SDT BIGINT NOT NULL,
    NUOC NVARCHAR(250) NOT NULL,
    GIOITINH NVARCHAR(50) NOT NULL,
    MADD VARCHAR (250) NOT NULL,
	SODEM INT NOT NULL,
    DIACHI NVARCHAR (350) NOT NULL,
    CHECKIN DATETIME NOT NULL,
    CHECKOU DATETIME,
    CHEKOU VARCHAR (250) DEFAULT ('NO'),
    TONGTIEN DECIMAL(18, 2),
    MAPHONG INT NULL,  -- ✅ Cho phép NULL
    CONSTRAINT FK_MAPHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG) ON DELETE SET NULL
);

CREATE TABLE NHANVIEN(
MANV INT IDENTITY (1, 1) NOT NULL,
TENNV NVARCHAR (250) NOT NULL,
SDTNV BIGINT  NOT NULL,
GIOITINHNV NVARCHAR (50)  NOT NULL,
EMAILNV VARCHAR (120) NOT NULL,

CHUCVU NVARCHAR(10) NOT NULL,
PRIMARY KEY CLUSTERED (MANV ASC)
);



CREATE TABLE HOADON (
    MAHD INT IDENTITY(1,1) PRIMARY KEY, -- Mã hóa đơn

    MAKH INT NOT NULL,  
	
    MANV INT NULL,                  -- Mã nhân viên lập hóa đơn
    MAPHONG INT NULL,                   -- ✅ Cho phép NULL nếu phòng bị xóa

    NGAYTHANHTOAN DATETIME,
    TONGTIEN DECIMAL(18,2) NOT NULL,
    PHUONGTHUCTT NVARCHAR(50) NOT NULL,

    -- Khóa ngoại
    CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE SET NULL,
    CONSTRAINT FK_HD_P  FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG) ON DELETE SET NULL
);






CREATE VIEW V_HOADON_VIEW AS
SELECT 
    HD.MAHD,
    HD.NGAYTHANHTOAN,
    HD.TONGTIEN,
    HD.PHUONGTHUCTT,
    (SELECT TENKH FROM KHACHHANG WHERE MAKH = HD.MAKH) AS TENKH,
    (SELECT TENNV FROM NHANVIEN WHERE MANV = HD.MANV) AS TENNHANVIEN,
    (SELECT SOPHONG FROM PHONG WHERE MAPHONG = HD.MAPHONG) AS SOPHONG
FROM HOADON HD




