create DATABASE QL_KS2

use QL_KS2

drop table NHANVIEN
drop table HOADON
drop table KHACHHANG
drop table PHONG
drop table TAIKHOAN

create table TAIKHOAN(
TENTK VARCHAR(150) NOT NULL,
MATKHAU VARCHAR(150) NOT NULL,

MANV INT NOT NULL,
CONSTRAINT PK_TAIKHOAN PRIMARY KEY (MANV),
CONSTRAINT FK_TAIKHOAN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)
CREATE TABLE PHONG(
MAPHONG INT IDENTITY(1,1) PRIMARY KEY,
SOPHONG VARCHAR(255) NOT NULL,
LOAIPHONG NVARCHAR(250) NOT NULL,

GIUONG NVARCHAR(250) NOT NULL,
GIA BIGINT NOT NULL,
DATPHONG VARCHAR (50) DEFAULT('NO') NULL
);

CREATE TABLE KHACHHANG(
    MAKH INT IDENTITY(1,1) PRIMARY KEY,
    TENKH NVARCHAR(250) NOT NULL,
    SDT BIGINT NOT NULL,
    NUOC NVARCHAR(250) NOT NULL,
    GIOITINH NVARCHAR(50) NOT NULL,
    MADD VARCHAR (250) NOT NULL,
	SODEM INT NOT NULL,
    DIACHI NVARCHAR (350) NOT NULL,
    CHECKIN DATETIME NOT NULL,
    CHECKOU DATETIME,
    CHEKOU VARCHAR (250) DEFAULT ('NO'),
    TONGTIEN DECIMAL(18, 2),
    MAPHONG INT NULL,  -- ✅ Cho phép NULL
    CONSTRAINT FK_MAPHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG) ON DELETE SET NULL
);

CREATE TABLE NHANVIEN(
MANV INT IDENTITY (1, 1) NOT NULL,
TENNV NVARCHAR (250) NOT NULL,
SDTNV BIGINT  NOT NULL,
GIOITINHNV NVARCHAR (50)  NOT NULL,
EMAILNV VARCHAR (120) NOT NULL,

CHUCVU NVARCHAR(10) NOT NULL,
PRIMARY KEY CLUSTERED (MANV ASC)
);



CREATE TABLE HOADON (
    MAHD INT IDENTITY(1,1) PRIMARY KEY, -- Mã hóa đơn

    MAKH INT NOT NULL,  
	
    MANV INT NULL,                  -- Mã nhân viên lập hóa đơn
    MAPHONG INT NULL,                   -- ✅ Cho phép NULL nếu phòng bị xóa

    NGAYTHANHTOAN DATETIME,
    TONGTIEN DECIMAL(18,2) NOT NULL,
    PHUONGTHUCTT NVARCHAR(50) NOT NULL,

    -- Khóa ngoại
    CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE SET NULL,
    CONSTRAINT FK_HD_P  FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG) ON DELETE SET NULL
);






CREATE VIEW V_HOADON_VIEW AS
SELECT 
    HD.MAHD,
    HD.NGAYTHANHTOAN,
    HD.TONGTIEN,
    HD.PHUONGTHUCTT,
    (SELECT TENKH FROM KHACHHANG WHERE MAKH = HD.MAKH) AS TENKH,
    (SELECT TENNV FROM NHANVIEN WHERE MANV = HD.MANV) AS TENNHANVIEN,
    (SELECT SOPHONG FROM PHONG WHERE MAPHONG = HD.MAPHONG) AS SOPHONG
FROM HOADON HD




SELECT GIA FROM PHONG WHERE SOPHONG = '3'

----------------------ThongTinCaNhan----------------------
	--Hiển thị thông tin cá nhân
	SELECT nv.TENNV,nv.SDTNV,nv.GIOITINHNV,nv.EMAILNV,tk.TENTK,tk.MATKHAU
    FROM NHANVIEN nv
	JOIN TAIKHOAN tk ON nv.MANV = tk.MANV
    WHERE nv.MANV = 1
-----------------------AddRoom---------------------------
	-- Hiển thị thông tin phòng
	select 
	MAPHONG AS [Mã Phòng],
	SOPHONG AS [Số Phòng],
	LOAIPHONG AS [Loại Phòng],
	GIUONG AS [Giường],
	GIA AS [Gía],
	DATPHONG AS [Trạng thái đặt phòng]
	from PHONG

	--Kiểm tra phòng
	SELECT COUNT(*) FROM PHONG WHERE SOPHONG = '{sophong}'

	--Cập nhật thông tin phòng
	UPDATE PHONG SET SOPHONG='1', LOAIPHONG='Vip', GIUONG='Đơn', GIA=10000000 
	WHERE MAPHONG=1



	-----------------Customer Detail----------------
	--Tìm mã phòng từ số phòng
	SELECT MAPHONG FROM PHONG WHERE SOPHONG = '1'

	--Cập nhật lại trạng phòng
	UPDATE PHONG SET DATPHONG = 'NO' WHERE MAPHONG = 1

	--Xóa khách hàng
	DELETE FROM KHACHHANG WHERE MAKH = 1


	--Cập nhật thông tin khách hàng
	UPDATE KHACHHANG SET
    TENKH = N'Nguyễn Tấn Dương',
    SDT = '123456889',
    NUOC = N'Việt Nam',
    GIOITINH = N'Nam',
    MADD = N'KH01',
    DIACHI = N'Phước tỉnh',
    SODEM = '2'
    WHERE MAKH = 1

	--Hiển thị thông tin khách hàng còn trong khách sạn
	SELECT KHACHHANG.MAKH AS[Mã Khách Hàng],
	KHACHHANG.TENKH AS [Tên Khách Hàng],
	KHACHHANG.SDT AS [Số điện thoại],
	KHACHHANG.NUOC AS[Nước],
	KHACHHANG.GIOITINH AS[Giới Tính],
	KHACHHANG.MADD AS[Mã Định Danh],
	KHACHHANG.DIACHI AS[Địa Chỉ],
	KHACHHANG.SODEM AS[Số Đêm],
	KHACHHANG.CHECKIN AS[Ngày đặt phòng],
	KHACHHANG.CHECKOU AS[Ngày Thanh Toán],
	KHACHHANG.TONGTIEN AS[Tổng Tiền],
	PHONG.SOPHONG AS[Số Phòng],
	PHONG.LOAIPHONG AS[Loại Phòng],
	PHONG.GIUONG AS[Giường],
	PHONG.GIA AS[Gía]
	FROM KHACHHANG
	INNER JOIN PHONG ON KHACHHANG.MAPHONG = PHONG.MAPHONG
	WHERE CHECKOU IS NULL





	-----------Customer Reg--------------
	--Cập nhật trạng thái phòng thành YES
	UPDATE PHONG 
    SET DATPHONG = 'YES' 
    WHERE SOPHONG = '1'
	--Hiển thị số phòng chưa đặt
	SELECT SOPHONG
	FROM PHONG
	WHERE GIUONG = N'Đôi' AND LOAIPHONG = N'Đôi' AND DATPHONG = 'NO'

	--Hiển thị giá,mã phòng
	SELECT GIA, MAPHONG
	FROM PHONG
	WHERE SOPHONG = '1'

	---------------Checkout-----------------
	--Hiển thị danh sách thông tin thanh toán
	select KHACHHANG.MAKH AS [Mã khách hàng],
	KHACHHANG.TENKH AS [Tên khách hàng],
	KHACHHANG.SDT AS [Số điện thoại],
	KHACHHANG.NUOC AS [Nước],
	KHACHHANG.GIOITINH AS[Giới Tính],
	KHACHHANG.MADD AS [Mã Định Danh],
	KHACHHANG.DIACHI AS [Địa Chỉ],
	KHACHHANG.CHECKIN AS[Ngày Đặt Phòng],
	KHACHHANG.TONGTIEN AS[Tổng Tiền],
	PHONG.SOPHONG AS [Số Phòng],
	PHONG.LOAIPHONG AS[Loại Phòng],
	KHACHHANG.SODEM AS[Số Đêm],
	PHONG.GIUONG AS[Giường],
	PHONG.GIA AS[Gía]
	from KHACHHANG 
	inner join PHONG on KHACHHANG.MAPHONG = PHONG.MAPHONG 
	where CHEKOU = 'NO'

	--Hiển thị thanh toán theo tìm kiếm theo tên khách hàng
	select KHACHHANG.MAKH AS [Mã khách hàng],
	KHACHHANG.TENKH AS [Tên khách hàng],
	KHACHHANG.SDT AS [Số điện thoại],
	KHACHHANG.NUOC AS [Nước],
	KHACHHANG.GIOITINH AS[Giới Tính],
	KHACHHANG.MADD AS [Mã Định Danh],
	KHACHHANG.DIACHI AS [Địa Chỉ],
	KHACHHANG.CHECKIN AS[Ngày Đặt Phòng],
	KHACHHANG.TONGTIEN AS[Tổng Tiền],
	PHONG.SOPHONG AS [Số Phòng],
	PHONG.LOAIPHONG AS[Loại Phòng],
	KHACHHANG.SODEM AS[Số Đêm],
	PHONG.GIUONG AS[Giường],
	PHONG.GIA AS[Gía] 
	from KHACHHANG 
	inner join PHONG on KHACHHANG.MAPHONG = PHONG.MAPHONG 
	where TENKH like N'Nguyễn Tấn Dương' and CHEKOU = 'NO'

	--Lấy mã phòng tư số phòng
	SELECT MAPHONG
	FROM PHONG
	WHERE SOPHONG = '1'

	--Cập nhật thái phòng thành NO
	UPDATE PHONG 
    SET DATPHONG = 'NO' 
    WHERE MAPHONG = 1;

	--Cập nhật khách hàng
	UPDATE KHACHHANG 
    SET CHEKOU = 'YES', CHECKOU = '2025-11-26', TONGTIEN = 1234456
    WHERE MAKH = 1;

	
	----------------Emplyee---------------------
	--Lấy mã nhân viên mới nhất
	select max(MANV)
	from NHANVIEN

	--Hiển thị thông tin nhân viên
	SELECT nv.MANV AS [Mã Nhân Viên],
	nv.TENNV AS [Tên Nhân Viên],
	nv.SDTNV AS [Số điện thoại],
	nv.GIOITINHNV AS [Giới Tính],
	nv.EMAILNV AS [Email],
	nv.CHUCVU AS [Chức Vụ],
    tk.TENTK AS [Tên Tài Khoản],
	tk.MATKHAU AS [Mật Khẩu]
    FROM NHANVIEN nv
    LEFT JOIN TAIKHOAN tk ON nv.MANV = tk.MANV

	--Cập nhật thông tin nhân viên
	 UPDATE NHANVIEN SET 
     TENNV = N'Nguyễn Tấn Dương', 
     SDTNV = '23553454543', 
     GIOITINHNV = N'Nam', 
     EMAILNV = N'duongnguy@gmail.com' 
     WHERE MANV = 6 

	 
	 ------------------HoaDon---------------------
	 --Hiển thị danh sách hóa đơn
	 SELECT 
     'HD' + RIGHT('000' + CAST(MAHD AS VARCHAR), 3) AS [Mã HĐ],
     KH.TENKH AS [Khách hàng],
     NV.TENNV AS [Nhân viên],
     P.SOPHONG AS [Phòng],
     HD.NGAYTHANHTOAN AS [Ngày thanh toán],
     HD.TONGTIEN AS [Tổng tiền],
     HD.PHUONGTHUCTT AS [Phương thức]
     FROM HOADON HD
     LEFT JOIN KHACHHANG KH ON HD.MAKH = KH.MAKH
     LEFT JOIN NHANVIEN NV ON HD.MANV = NV.MANV
     LEFT JOIN PHONG P ON HD.MAPHONG = P.MAPHONG

	 --Lọc hóa đơn theo ngày
	 SELECT 
     'HD' + RIGHT('000' + CAST(MAHD AS VARCHAR), 3) AS [Mã HĐ],
     KH.TENKH AS [Khách hàng],
     NV.TENNV AS [Nhân viên],
     P.SOPHONG AS [Phòng],
     HD.NGAYTHANHTOAN AS [Ngày thanh toán],
     HD.TONGTIEN AS [Tổng tiền],
     HD.PHUONGTHUCTT AS [Phương thức]
     FROM HOADON HD
     JOIN KHACHHANG KH ON HD.MAKH = KH.MAKH
     JOIN NHANVIEN NV ON HD.MANV = NV.MANV
     JOIN PHONG P ON HD.MAPHONG = P.MAPHONG
     WHERE CAST(HD.NGAYTHANHTOAN AS DATE) = '2025-08-01'


-----------------------ThongKe------------------
  --Hiển thị thống kê
  SELECT * FROM V_HOADON_VIEW

  CREATE VIEW V_HOADON_VIEW AS
SELECT DISTINCT
    HD.MAHD,
    KH.TENKH,
    P.SOPHONG,
    NV.TENNV AS TENNHANVIEN,
    HD.NGAYTHANHTOAN,
    HD.TONGTIEN,
    HD.PHUONGTHUCTT
FROM HOADON HD
JOIN KHACHHANG KH ON HD.MAKH = KH.MAKH
JOIN PHONG P ON HD.MAPHONG = P.MAPHONG
JOIN NHANVIEN NV ON HD.MANV = NV.MANV;

	--Lọc hóa đơn
	 SELECT 'HD' + RIGHT('000' + CAST(MAHD AS VARCHAR), 3) AS MAHD_HIEN,
     KH.TENKH, P.SOPHONG, NV.TENNV AS TENNHANVIEN,HD.NGAYTHANHTOAN, HD.TONGTIEN, HD.PHUONGTHUCTT
     FROM HOADON HD
     JOIN KHACHHANG KH ON HD.MAKH = KH.MAKH
     JOIN PHONG P ON HD.MAPHONG = P.MAPHONG
     JOIN NHANVIEN NV ON HD.MANV = NV.MANV
     WHERE HD.NGAYTHANHTOAN BETWEEN '2025-07-25' AND '2025-08-20'


	 SELECT 
    LOAIPHONG AS [Loại Phòng],
    COUNT(*) AS [Số Lượng Phòng]
FROM PHONG
GROUP BY LOAIPHONG;


SELECT 
    LOAIPHONG AS [Loại Phòng],
    COUNT(*) AS [Số Lượng Phòng]
FROM PHONG
GROUP BY LOAIPHONG
HAVING COUNT(*) >= 5;



--RIGHT JOIN 
SELECT 
    nv.MANV,
    nv.TENNV,
    tk.TENTK,
    tk.MATKHAU
FROM NHANVIEN nv
RIGHT JOIN TAIKHOAN tk
    ON nv.MANV = tk.MANV;


INSERT INTO NHANVIEN (TENNV, SDTNV, GIOITINHNV, EMAILNV, CHUCVU)
VALUES
(N'Nguyễn Văn A', 123456789, N'Nam', 'vana@gmail.com', N'Quản lý'),
(N'Lê Thị B', 987654321, N'Nữ', 'thib@gmail.com', N'Lễ tân'),
(N'Phạm Văn C', 555666777, N'Nam', 'vanc@gmail.com', N'Bảo vệ');   -- người này KHÔNG có tài khoản

INSERT INTO TAIKHOAN (TENTK, MATKHAU, MANV)
VALUES
('admin', '123456', 1);
('letan01', 'abc123', 2);


--FULL JOIN - Hiển thị tất cả dữ liệu 2 bảng 
SELECT
    nv.MANV AS MANV_NV,
    nv.TENNV,
    tk.MANV AS MANV_TK,
    tk.TENTK,
    tk.MATKHAU
FROM NHANVIEN nv
FULL JOIN TAIKHOAN tk ON nv.MANV = tk.MANV;
